// <auto-generated />
using System;
using CDM.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CDM.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251125205647_AddResetPasswordFields")]
    partial class AddResetPasswordFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CDM.Database.Models.AppelDeFond", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoproprietaireId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MontantDu")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantRegle")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Regularisation")
                        .HasColumnType("TEXT");

                    b.Property<int>("TrimestreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CoproprietaireId");

                    b.HasIndex("TrimestreId");

                    b.ToTable("AppelsDeFonds");
                });

            modelBuilder.Entity("CDM.Database.Models.ChargeTrimestre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantPrevisionnel")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantReel")
                        .HasColumnType("TEXT");

                    b.Property<int>("TrimestreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrimestreId");

                    b.ToTable("ChargeTrimestres");
                });

            modelBuilder.Entity("CDM.Database.Models.ChargeTrimestreSousCopro", b =>
                {
                    b.Property<int>("ChargeTrimestreId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SousCoproprieteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChargeTrimestreId", "SousCoproprieteId");

                    b.HasIndex("SousCoproprieteId");

                    b.ToTable("ChargeTrimestreSousCopros");
                });

            modelBuilder.Entity("CDM.Database.Models.Coproprietaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResetPasswordTokenExpiration")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nom");

                    b.ToTable("Coproprietaires");
                });

            modelBuilder.Entity("CDM.Database.Models.Lot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoproprietaireId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeroLot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SousCoproprieteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tantiemes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CoproprietaireId");

                    b.HasIndex("NumeroLot")
                        .IsUnique();

                    b.HasIndex("SousCoproprieteId");

                    b.ToTable("Lots");
                });

            modelBuilder.Entity("CDM.Database.Models.SousCopropriete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SousCoproprietes");
                });

            modelBuilder.Entity("CDM.Database.Models.Trimestre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Annee")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstValide")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrevisionnel")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalReel")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Trimestres");
                });

            modelBuilder.Entity("CDM.Database.Models.AppelDeFond", b =>
                {
                    b.HasOne("CDM.Database.Models.Coproprietaire", "Coproprietaire")
                        .WithMany()
                        .HasForeignKey("CoproprietaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CDM.Database.Models.Trimestre", "Trimestre")
                        .WithMany("AppelsDeFonds")
                        .HasForeignKey("TrimestreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coproprietaire");

                    b.Navigation("Trimestre");
                });

            modelBuilder.Entity("CDM.Database.Models.ChargeTrimestre", b =>
                {
                    b.HasOne("CDM.Database.Models.Trimestre", "Trimestre")
                        .WithMany("Charges")
                        .HasForeignKey("TrimestreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trimestre");
                });

            modelBuilder.Entity("CDM.Database.Models.ChargeTrimestreSousCopro", b =>
                {
                    b.HasOne("CDM.Database.Models.ChargeTrimestre", "ChargeTrimestre")
                        .WithMany("SousCopros")
                        .HasForeignKey("ChargeTrimestreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CDM.Database.Models.SousCopropriete", "SousCopropriete")
                        .WithMany("ChargeAssociations")
                        .HasForeignKey("SousCoproprieteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargeTrimestre");

                    b.Navigation("SousCopropriete");
                });

            modelBuilder.Entity("CDM.Database.Models.Lot", b =>
                {
                    b.HasOne("CDM.Database.Models.Coproprietaire", "Coproprietaire")
                        .WithMany("Lots")
                        .HasForeignKey("CoproprietaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CDM.Database.Models.SousCopropriete", "SousCopropriete")
                        .WithMany("Lots")
                        .HasForeignKey("SousCoproprieteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coproprietaire");

                    b.Navigation("SousCopropriete");
                });

            modelBuilder.Entity("CDM.Database.Models.ChargeTrimestre", b =>
                {
                    b.Navigation("SousCopros");
                });

            modelBuilder.Entity("CDM.Database.Models.Coproprietaire", b =>
                {
                    b.Navigation("Lots");
                });

            modelBuilder.Entity("CDM.Database.Models.SousCopropriete", b =>
                {
                    b.Navigation("ChargeAssociations");

                    b.Navigation("Lots");
                });

            modelBuilder.Entity("CDM.Database.Models.Trimestre", b =>
                {
                    b.Navigation("AppelsDeFonds");

                    b.Navigation("Charges");
                });
#pragma warning restore 612, 618
        }
    }
}
